config/routes.rb
APGovPoll::Application.routes.draw do
  resources :poll_responses

end

app/models/poll_response.rb
class PollResponse < ActiveRecord::Base
  attr_accessible :age, :candidate, :gender, :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/poll_responses_controller.rb
class PollResponsesController < ApplicationController
  # GET /poll_responses
  # GET /poll_responses.json
  def index
    @poll_responses = PollResponse.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @poll_responses }
    end
  end

  # GET /poll_responses/1
  # GET /poll_responses/1.json
  def show
    @poll_response = PollResponse.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @poll_response }
    end
  end

  # GET /poll_responses/new
  # GET /poll_responses/new.json
  def new
    @poll_response = PollResponse.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @poll_response }
    end
  end

  # GET /poll_responses/1/edit
  def edit
    @poll_response = PollResponse.find(params[:id])
  end

  # POST /poll_responses
  # POST /poll_responses.json
  def create
    @poll_response = PollResponse.new(params[:poll_response])

    respond_to do |format|
      if @poll_response.save
        format.html { redirect_to @poll_response, notice: 'Poll response was successfully created.' }
        format.json { render json: @poll_response, status: :created, location: @poll_response }
      else
        format.html { render action: "new" }
        format.json { render json: @poll_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /poll_responses/1
  # PUT /poll_responses/1.json
  def update
    @poll_response = PollResponse.find(params[:id])

    respond_to do |format|
      if @poll_response.update_attributes(params[:poll_response])
        format.html { redirect_to @poll_response, notice: 'Poll response was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @poll_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poll_responses/1
  # DELETE /poll_responses/1.json
  def destroy
    @poll_response = PollResponse.find(params[:id])
    @poll_response.destroy

    respond_to do |format|
      format.html { redirect_to poll_responses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poll_responses_helper.rb
module PollResponsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>APGovPoll</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/poll_responses/_form.html.erb
<%= form_for(@poll_response) do |f| %>
  <% if @poll_response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll_response.errors.count, "error") %> prohibited this poll_response from being saved:</h2>

      <ul>
      <% @poll_response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :candidate %><br />
    <%= f.text_field :candidate %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poll_responses/edit.html.erb
<h1>Editing poll_response</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll_response %> |
<%= link_to 'Back', poll_responses_path %>

app/views/poll_responses/index.html.erb
<h1>Listing poll_responses</h1>

<table>
  <tr>
    <th>Candidate</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @poll_responses.each do |poll_response| %>
  <tr>
    <td><%= poll_response.candidate %></td>
    <td><%= poll_response.gender %></td>
    <td><%= poll_response.age %></td>
    <td><%= poll_response.location %></td>
    <td><%= link_to 'Show', poll_response %></td>
    <td><%= link_to 'Edit', edit_poll_response_path(poll_response) %></td>
    <td><%= link_to 'Destroy', poll_response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Poll response', new_poll_response_path %>

app/views/poll_responses/new.html.erb
<h1>New poll_response</h1>

<%= render 'form' %>

<%= link_to 'Back', poll_responses_path %>

app/views/poll_responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Candidate:</b>
  <%= @poll_response.candidate %>
</p>

<p>
  <b>Gender:</b>
  <%= @poll_response.gender %>
</p>

<p>
  <b>Age:</b>
  <%= @poll_response.age %>
</p>

<p>
  <b>Location:</b>
  <%= @poll_response.location %>
</p>


<%= link_to 'Edit', edit_poll_response_path(@poll_response) %> |
<%= link_to 'Back', poll_responses_path %>